# Generated by Django 4.2.7 on 2025-09-24 15:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary (little/no exercise)'), ('light', 'Lightly active (light exercise 1-3 days/week)'), ('moderate', 'Moderately active (moderate exercise 3-5 days/week)'), ('very', 'Very active (hard exercise 6-7 days/week)'), ('extra', 'Extra active (very hard exercise, physical job)')], default='moderate', max_length=20)),
                ('primary_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain_weight', 'Maintain Weight'), ('gain_weight', 'Gain Weight'), ('build_muscle', 'Build Muscle'), ('improve_health', 'Improve Overall Health')], default='improve_health', max_length=20)),
                ('daily_calorie_goal', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_protein_goal', models.FloatField(blank=True, null=True)),
                ('daily_carbs_goal', models.FloatField(blank=True, null=True)),
                ('daily_fat_goal', models.FloatField(blank=True, null=True)),
                ('dietary_restrictions', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
